language: en
pipeline:
- name: "SpacyNLP"
- name: "WhitespaceTokenizer"
- name: "RegexFeaturizer"
- name: "LexicalSyntacticFeaturizer"
- name: "DIETClassifier"
policies:
- name: "MemoizationPolicy"
- name: "TEDPolicy"
assistant_id: 20241129-225355-median-soul
