language: en
pipeline:
  - name: "SpacyNLP"
  - name: "WhitespaceTokenizer"
  - name: "RegexFeaturizer"
  - name: "LexicalSyntacticFeaturizer"
  - name: "DIETClassifier"
policies:
  - name: "MemoizationPolicy"
  - name: "TEDPolicy"
