language: en
pipeline:
  - name: SpacyNLP
    model: "en_core_web_md"
  - name: SpacyTokenizer
  - name: RegexFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
  - name: EntitySynonymMapper
  - name: ResponseSelector
policies:
  - name: "MemoizationPolicy"
  - name: "TEDPolicy"
  - name: "RulePolicy"
    max_failed: 5  # increase the max_failed limit if needed
assistant_id: 20241129-225355-median-soul
